server:
  port: 9093
dubbo:
# dubbo应用名称 对应车牌号 司机姓名 车类型
  application:
    name: service-provider
  registry:
    address: zookeeper://8.130.41.226:2181  #注册中心地址
  protocol:
    name: dubbo
    port: 20883
