server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://8.130.41.226:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Aa@123456
mybatis:
  type-aliases-package: com.qfedu.cloud.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl