server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://8.130.41.226:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Aa@123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.qfedu.cloud.model
eureka:
  client:
    service-url: #EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka