server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.130.41.226:3306/chuangan?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Aa@123456
  redis:
    host: 8.130.41.226
    password: 123
    jedis:
      pool:
        max-idle: 8
    database: 8
mybatis-plus:
  type-aliases-package: com.qfedu.iot.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
data:
  basic: 10  #初始值gging.stdout.StdOutImpl